### ISSUE TITLE
Crash on Switch A 17.0.1

### ISSUE THREAD

**Issue by hawkiq** [RSDuck/duckstation#8]
### Game details

Duckstation prerelease-2

### Description of the issue/bug

I followed the instruction to install duckstation on switch , I face a problem that my app get crash I get this error
![photo_2024-05-22_17-37-48](https://github.com/RSDuck/duckstation/assets/7524502/be952695-a22d-4517-8999-56e9c88d9f9b)

### Steps to reproduce

Running app from applet mode.

### Software and hardware information

Nintendo Switch CFW 17.0.1

### DuckStation version

prerelease-2

### DuckStation rendering backend

Software

### DuckStation controller backend, drivers and wrappers

None

**Comment by bocaskt** [comment]
Same error here!

**Comment by RSDuck** [comment]
well don't use applet mode and don't use nsps.  https://github.com/RSDuck/duckstation/commit/521aa8b79dbd5d854311f705a8ecc9ca58758b61 adds an error message to be displayed when apple mode is used.
